version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_broker
    networks:
      - idrl-network
  
  db:
    image: postgres
    container_name: fpv_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fpv_db
    networks:
      - idrl-network
    ports: 
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data

  user:
    build: ./user
    container_name: user
    volumes:
      - ./user:/app
    networks:
      - idrl-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - 81:80
    depends_on:
      - user
    networks:
      - idrl-network

networks:
  idrl-network:
    driver: bridge

volumes: 
  postgres-data: 
    driver: local
