version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_broker
    networks:
      - idrl-network

  user:
    build: ./user
    container_name: user
    volumes:
      - ./user:/app
    networks:
      - idrl-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - user
    networks:
      - idrl-network

networks:
  idrl-network:
