version: "3.9"

services:
  redis:
    image: redis:alpine
    container_name: redis_broker
    networks:
      - idrl-network

  usuario:
    build: ./usuario
    container_name: usuario
    volumes:
      - ./usuario:/app
    networks:
      - idrl-network

  api-gateway:
    image: nginx:latest
    container_name: api-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - usuario
    networks:
      - idrl-network

networks:
  idrl-network:
